### ISSUE TITLE
Versions 0.5.2 and below can access self-hosted sharelatex projects normally, but versions 0.5.3 and above cannot.

### ISSUE THREAD

**Issue by fbotp** [iamhyc/Overleaf-Workshop#74]
### Describe the bug
> When installing versions 0.5.3 and above, you can log in to self-hosted sharelatex normally through passwords and cookies, but you cannot enter the project.

### Expected behavior
> Ability to browse files in self-hosted sharelatex projects.

### How To Reproduce
> Install version 0.5.3 and above, add a self-hosted server and log in, then try to enter any of the listed projects to reproduce.

### Environment
 - **Overleaf Workshop Extension version**:[ 0.5.3 and above]
 - **VS Code version**: [1.85.1]
 - **Overleaf Edition**: Community, installed by docker pull sharelatex/sharelatex:4.2.0

### [Optional] Developer Logs
> Error: Error: unexpected server response (502)
	at SocketNamespace.<anonymous> (c:\Users\zy\.vscode\extensions\iamhyc.overleaf-workshop-0.7.1\out\api\socketio.js:70:19)
	at EventEmitter.emit [as $emit] (c:\Users\zy\.vscode\extensions\iamhyc.overleaf-workshop-0.7.1\node_modules\socket.io-client\lib\events.js:165:15)
	at Socket.publish (c:\Users\zy\.vscode\extensions\iamhyc.overleaf-workshop-0.7.1\node_modules\socket.io-client\lib\socket.js:103:19)
	at Socket.onError (c:\Users\zy\.vscode\extensions\iamhyc.overleaf-workshop-0.7.1\node_modules\socket.io-client\lib\socket.js:485:10)
	at WS.onError (c:\Users\zy\.vscode\extensions\iamhyc.overleaf-workshop-0.7.1\node_modules\socket.io-client\lib\transports\websocket.js:148:17)
	at websocket.onerror (c:\Users\zy\.vscode\extensions\iamhyc.overleaf-workshop-0.7.1\node_modules\socket.io-client\lib\transports\websocket.js:82:12)
	at WebSocket.onError (c:\Users\zy\.vscode\extensions\iamhyc.overleaf-workshop-0.7.1\node_modules\ws\lib\WebSocket.js:452:14)
	at WebSocket.emit (node:events:513:28)
	at ClientRequest.response (c:\Users\zy\.vscode\extensions\iamhyc.overleaf-workshop-0.7.1\node_modules\ws\lib\WebSocket.js:721:12)
	at Object.onceWrapper (node:events:628:26)
	at ClientRequest.emit (node:events:525:35)
	at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:701:27)
	at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
	at Socket.socketOnData (node:_http_client:542:22)
	at Socket.emit (node:events:513:28)
	at addChunk (node:internal/streams/readable:324:12)
	at readableAddChunk (node:internal/streams/readable:297:9)
	at Readable.push (node:internal/streams/readable:234:10)
	at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
> rejected promise not handled within 1 second: TypeError: Invalid host defined options
> stack trace: TypeError: Invalid host defined options
	at Object.<anonymous> (c:\Users\zy\.vscode\extensions\iamhyc.overleaf-workshop-0.7.1\node_modules\prettier\index.cjs:593:23)
	at o._compile (d:\Microsoft VS Code\resources\app\out\vs\loader.js:4:1271)
	at Module._extensions..js (node:internal/modules/cjs/loader:1371:10)
	at Module.load (node:internal/modules/cjs/loader:1171:32)
	at Module._load (node:internal/modules/cjs/loader:1012:12)
	at f._load (node:electron/js2c/asar_bundle:2:13377)
	at c._load (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:171:5632)
	at n._load (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:168:29551)
	at t._load (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:133:35226)
	at Module.require (node:internal/modules/cjs/loader:1195:19)
	at h (d:\Microsoft VS Code\resources\app\out\vs\loader.js:4:647)
	at Object.<anonymous> (c:\Users\zy\.vscode\extensions\iamhyc.overleaf-workshop-0.7.1\out\intellisense\texDocFormatter.js:5:18)
	at o._compile (d:\Microsoft VS Code\resources\app\out\vs\loader.js:4:1271)
	at Module._extensions..js (node:internal/modules/cjs/loader:1371:10)
	at Module.load (node:internal/modules/cjs/loader:1171:32)
	at Module._load (node:internal/modules/cjs/loader:1012:12)
	at f._load (node:electron/js2c/asar_bundle:2:13377)
	at c._load (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:171:5632)
	at n._load (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:168:29551)
	at t._load (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:133:35226)
	at Module.require (node:internal/modules/cjs/loader:1195:19)
	at h (d:\Microsoft VS Code\resources\app\out\vs\loader.js:4:647)
	at Object.<anonymous> (c:\Users\zy\.vscode\extensions\iamhyc.overleaf-workshop-0.7.1\out\intellisense\langIntellisenseProvider.js:9:27)
	at o._compile (d:\Microsoft VS Code\resources\app\out\vs\loader.js:4:1271)
	at Module._extensions..js (node:internal/modules/cjs/loader:1371:10)
	at Module.load (node:internal/modules/cjs/loader:1171:32)
	at Module._load (node:internal/modules/cjs/loader:1012:12)
	at f._load (node:electron/js2c/asar_bundle:2:13377)
	at c._load (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:171:5632)
	at n._load (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:168:29551)
	at t._load (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:133:35226)
	at Module.require (node:internal/modules/cjs/loader:1195:19)
	at h (d:\Microsoft VS Code\resources\app\out\vs\loader.js:4:647)
	at Object.<anonymous> (c:\Users\zy\.vscode\extensions\iamhyc.overleaf-workshop-0.7.1\out\extension.js:10:36)
	at o._compile (d:\Microsoft VS Code\resources\app\out\vs\loader.js:4:1271)
	at Module._extensions..js (node:internal/modules/cjs/loader:1371:10)
	at Module.load (node:internal/modules/cjs/loader:1171:32)
	at Module._load (node:internal/modules/cjs/loader:1012:12)
	at f._load (node:electron/js2c/asar_bundle:2:13377)
	at c._load (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:171:5632)
	at n._load (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:168:29551)
	at t._load (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:133:35226)
	at Module.require (node:internal/modules/cjs/loader:1195:19)
	at require (node:internal/modules/cjs/helpers:110:18)
	at Function.i [as __$__nodeRequire] (d:\Microsoft VS Code\resources\app\out\vs\loader.js:5:98)
	at f.vb (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:168:30730)
	at async Promise.all (index 0)
> [iamhyc.overleaf-workshop]Invalid host defined options
> workbench.desktop.main.js:sourcemap:2017 TypeError: Invalid host defined options
	at Object.<anonymous> (c:\Users\zy\.vscode\extensions\iamhyc.overleaf-workshop-0.7.1\node_modules\prettier\index.cjs:593:23)
	at o._compile (d:\Microsoft VS Code\resources\app\out\vs\loader.js:4:1271)
	at Module._extensions..js (node:internal/modules/cjs/loader:1371:10)
	at Module.load (node:internal/modules/cjs/loader:1171:32)
	at Module._load (node:internal/modules/cjs/loader:1012:12)
	at f._load (node:electron/js2c/asar_bundle:2:13377)
	at c._load (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:171:5632)
	at n._load (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:168:29551)
	at t._load (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:133:35226)
	at Module.require (node:internal/modules/cjs/loader:1195:19)
	at h (d:\Microsoft VS Code\resources\app\out\vs\loader.js:4:647)
	at Object.<anonymous> (c:\Users\zy\.vscode\extensions\iamhyc.overleaf-workshop-0.7.1\out\intellisense\texDocFormatter.js:5:18)
	at o._compile (d:\Microsoft VS Code\resources\app\out\vs\loader.js:4:1271)
	at Module._extensions..js (node:internal/modules/cjs/loader:1371:10)
	at Module.load (node:internal/modules/cjs/loader:1171:32)
	at Module._load (node:internal/modules/cjs/loader:1012:12)
	at f._load (node:electron/js2c/asar_bundle:2:13377)
	at c._load (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:171:5632)
	at n._load (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:168:29551)
	at t._load (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:133:35226)
	at Module.require (node:internal/modules/cjs/loader:1195:19)
	at h (d:\Microsoft VS Code\resources\app\out\vs\loader.js:4:647)
	at Object.<anonymous> (c:\Users\zy\.vscode\extensions\iamhyc.overleaf-workshop-0.7.1\out\intellisense\langIntellisenseProvider.js:9:27)
	at o._compile (d:\Microsoft VS Code\resources\app\out\vs\loader.js:4:1271)
	at Module._extensions..js (node:internal/modules/cjs/loader:1371:10)
	at Module.load (node:internal/modules/cjs/loader:1171:32)
	at Module._load (node:internal/modules/cjs/loader:1012:12)
	at f._load (node:electron/js2c/asar_bundle:2:13377)
	at c._load (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:171:5632)
	at n._load (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:168:29551)
	at t._load (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:133:35226)
	at Module.require (node:internal/modules/cjs/loader:1195:19)
	at h (d:\Microsoft VS Code\resources\app\out\vs\loader.js:4:647)
	at Object.<anonymous> (c:\Users\zy\.vscode\extensions\iamhyc.overleaf-workshop-0.7.1\out\extension.js:10:36)
	at o._compile (d:\Microsoft VS Code\resources\app\out\vs\loader.js:4:1271)
	at Module._extensions..js (node:internal/modules/cjs/loader:1371:10)
	at Module.load (node:internal/modules/cjs/loader:1171:32)
	at Module._load (node:internal/modules/cjs/loader:1012:12)
	at f._load (node:electron/js2c/asar_bundle:2:13377)
	at c._load (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:171:5632)
	at n._load (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:168:29551)
	at t._load (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:133:35226)
	at Module.require (node:internal/modules/cjs/loader:1195:19)
	at require (node:internal/modules/cjs/helpers:110:18)
	at Function.i [as __$__nodeRequire] (d:\Microsoft VS Code\resources\app\out\vs\loader.js:5:98)
	at f.vb (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:168:30730)
	at async Promise.all (index 0)

**Comment by iamhyc** [comment]
Thanks for the report. I will have a quick look at it now.

**Comment by iamhyc** [comment]
@fbotp I found there is no changes related to `socket.io-client` API between `v0.5.2` and `v0.5.3`, except for a internal `timeout` exception which should not trigger 502 error.

Could you please attach the normal log starts with `SocketIOAPI`? Thank you.

**Comment by iamhyc** [comment]
I have just search 502 error for socketio client and found this link maybe helpful:

https://stackoverflow.com/questions/35698595/bad-gateway-error-using-socket-io-node-js-over-ssl

Please check if your server address is correctly using "http://" or "https://". "http://" maybe wrong for SSL-enabled server.

**Comment by fbotp** [comment]
@iamhyc Thank you for your reply. Now I am using `v0.5.2`. When I enter the project called `面向战略性新兴产业的专名标引方法研究`, the vscode log looks like this:
>  ![image](https://github.com/iamhyc/Overleaf-Workshop/assets/46618620/375d280f-d77a-4198-8e39-f4837b0f01e7)

where `192.168.3.149:6180` is self-hosted server ,and if I use `v0.5.3`, the log looks like:
> ![20240111191746](https://github.com/iamhyc/Overleaf-Workshop/assets/46618620/c9a47909-399a-4b3b-87b2-4378544d89b1)
As you see, the error keeps reoccurring and doesn't stop

I think below picture shows that I have logged in.
![image](https://github.com/iamhyc/Overleaf-Workshop/assets/46618620/98a62073-0b2a-4ebe-a11b-d1610e293e8e)

By the way, I'm sure my address is `http://192.168.3.149:6180/`. And if now I install `v0.5.2` and reload window, files in project would appearred normally.

**Comment by iamhyc** [comment]
Got it. That is weird. I will check on `sharelatex v4.2` later.

**Comment by fbotp** [comment]
thanks, waiting for your reply❤️

**Comment by iamhyc** [comment]
![image](https://github.com/iamhyc/Overleaf-Workshop/assets/9068301/443f3bc0-a7c4-4220-87f8-f8f8d58c76d2)

Cannot produce the bug on my side. I have to say this is really weird, especially considering there is no much difference between `v0.5.2` and `v0.5.3`.

**Comment by iamhyc** [comment]
Can you try to remove the server firstly, then add the server and login to see if it works?

**Comment by iamhyc** [comment]
Though it is not able to reproduced, I find the server may prefer `v2` connection by default.

Please have a try with the auto-generated temporary extension here: https://github.com/iamhyc/Overleaf-Workshop/actions/runs/7488723638?pr=75

It will use `v2` connection if the error is thrown.

**Comment by fbotp** [comment]
I tried remove serve and add again, I also use this temp extension, but it does't work.
I suddenly remembered that I ran the following commands within the sharelatex container:
```
tlmgr option repository https://mirrors.tuna.tsinghua.edu.cn/CTAN/systems/texlive/tlnet
tlmgr update --self --all
tlmgr install scheme-full
```
I'm not sure if it will affect this.

**Comment by fbotp** [comment]
I rechecked all my operations: pulled `sharelatex/sharelatex:4.2.0` from [hub.docker.com](hub.docker.com) using `overleaf-toolkit`, went into the container to install `scheme-full`, and created an admin user via `launchpad` , uploaded the project, then added the server in vscode, and tried to enter the project, and then found these error. Are there any operating errors?

**Comment by iamhyc** [comment]
> I rechecked all my operations: pulled `sharelatex/sharelatex:4.2.0` from [hub.docker.com](hub.docker.com) using `overleaf-toolkit`, went into the container to install `scheme-full`, and created an admin user via `launchpad` , uploaded the project, then added the server in vscode, and tried to enter the project, and then found these error. Are there any operating errors?

I did exactly the same thing, exccept to install `scheme-full`.

**Comment by iamhyc** [comment]
Please also help test the new temporary extension and attach the log: https://github.com/iamhyc/Overleaf-Workshop/actions/runs/7489218302

I found I made some mistake in last one.

**Comment by fbotp** [comment]
![5({(1X52_BCRH2T5R%~Q4RR](https://github.com/iamhyc/Overleaf-Workshop/assets/46618620/5f5fe094-5b5c-4ac6-a3cd-4aaee44859aa)
I used this extension and 502 errors keep appearing.

> Please also help test the new temporary extension and attach the log: https://github.com/iamhyc/Overleaf-Workshop/actions/runs/7489218302
> 
> I found I made some mistake in last one.

**Comment by iamhyc** [comment]
Ok, at lease we know there is nothing to do with `v2` api. The cause is still unknown.

**Comment by fbotp** [comment]
I'm trying to recreate a server without "scheme-full" to see if this has something to do with it

**Comment by fbotp** [comment]
I did these:
```
git clone https://github.com/overleaf/toolkit.git ./test
cd test
./bin/init
# then modify two variable in `config/overleaf.rc`, because server have no gui:
SHARELATEX_LISTEN_IP=0.0.0.0
SHARELATEX_PORT=6180

./bin/up
```
then visited `http://192.168.3.149:6180/launchpad` and create user, then created an example project named `test`, then added this server in vscode, and tried to enter this project. It still failed.

**Comment by iamhyc** [comment]
Just to make sure: have you tried `http://127.0.0.1:6180`?

**Comment by iamhyc** [comment]
> No, I ran this server on a linux server and visit it on my PC, so I don't know how to visited it by `http://127.0.0.1:6180`

Use vscode SSH-Remote Extension and then install this extension in remote.

**Comment by fbotp** [comment]
And then forward server:6180 to my PC:6180?

**Comment by iamhyc** [comment]
> I forawrd 6180 to PC localhost, and add server `http://127.0.0.1:6180`, it works, but why

I am not sure how you do the forward, but the websocket protocol maybe unstable in your environment. I guess.

**Comment by fbotp** [comment]
I found that, if I install extension on server, and connect to remote server by `Remote-SSH` first, then get into project, it works, so everytime I connect to overleaf, I need to ssh to server first?

**Comment by iamhyc** [comment]
I think the problem is: you can connect to the server via `127.0.0.1` but not `192.168.3.149`.

In my network environment, I can connect to it via both `127.0.1` and `100.64.0.3` (virtual LAN address).

So, I don't think this is a general issue and I suggest you check your network router firstly.

**Comment by fbotp** [comment]
But I feel a little strange, why can I access it through the web page but not through vscode? And there will be no problem logging in, getting the project list, creating a new project, or deleting the project.

**Comment by iamhyc** [comment]
> But I feel a little strange, why can I access it through the web page but not through vscode? And there will be no problem logging in, getting the project list, creating a new project, or deleting the project.

You make the reply so fast and I am still typing ...

Could you also let me know why? I am still curious about the difference between `v0.5.2` and `v0.5.3`

**Comment by fbotp** [comment]
Sorry, I installed `v2rayA` on my PC, and use `system proxy` mode, and config `RoutingA` as below:
> default: direct
domain(arxiv.org)->proxy
domain(debrepo.freedownloadmanager.org)->proxy
domain(files.pythonhosted.org)->proxy
domain(geosite:docker)->proxy
domain(geosite:facebook)->proxy
domain(geosite:github)->proxy
domain(geosite:google)->proxy
domain(geosite:medium)->proxy
domain(geosite:openai)->proxy
domain(geosite:quora)->proxy
domain(geosite:reddit)->proxy
domain(geosite:stackexchange)->proxy
domain(huggingface.co)->proxy
domain(ppa.launchpadcontent.net)->proxy
domain(pypi.org)->proxy
domain(steamcommunity.com)->proxy
domain(steampowered.com)->proxy
domain(steamunlocked.net)->proxy
domain(geosite:twitter)->proxy
domain(geosite:v2ray)->proxy
domain(v2ex.com)->proxy
domain(v2raya.org)->proxy
domain(www.popai.pro)->proxy
domain(chat.forefront.ai)->proxy
domain(geosite:wikimedia)->proxy

It seems that, if I set network proxy in windows, it does't work, but if I close it in Windows settings, it will be okay.

**Comment by iamhyc** [comment]
Yes, I should have warned you of the proxy thing firstly. Anyway, glad that you find the root cause!

**Comment by fbotp** [comment]
Yes, I changed `http.proxy support` to `off` in vscode, and everything works fine! Thank you for your patient answer!
